export const patients = [
  { id: 1, registeredDate: "2023-05-15", name: "Alice Johnson", age: 65, status: "Active", budget: "$3000-$3999", medicalConditions: ["Hypertension", "Type 2 Diabetes"], ambulatory: "Yes", location: "123 Oak Street, San Francisco, CA 94110", gender: "Female", diagnosis: ["Hypertension", "Type 2 Diabetes"], medications: ["Lisinopril", "Metformin"], careNeeds: ["Blood pressure monitoring", "Blood sugar management"], notes: "Patient manages conditions well with medication adherence", admissionDate: "2023-05-15", roomNumber: "101" },
  { id: 2, registeredDate: "2023-06-22", name: "Bob Smith", age: 72, status: "Pending", budget: "$4000-$4999", medicalConditions: ["COPD"], ambulatory: "No", location: "456 Pine Avenue, San Francisco, CA 94115", gender: "Male", diagnosis: ["COPD", "Respiratory Insufficiency"], medications: ["Albuterol", "Spiriva"], careNeeds: ["Oxygen therapy", "Respiratory monitoring"], notes: "Requires regular breathing treatments and oxygen support", admissionDate: "2023-06-22", roomNumber: "102" },
  { id: 3, registeredDate: "2023-07-03", name: "Carol Williams", age: 78, status: "Inactive", budget: "Below $2000", medicalConditions: ["Arthritis", "Depression"], ambulatory: "Yes", location: "789 Maple Drive, San Francisco, CA 94122", gender: "Female", diagnosis: ["Rheumatoid Arthritis", "Major Depression"], medications: ["Methotrexate", "Sertraline"], careNeeds: ["Joint mobility exercises", "Mental health support"], notes: "Showing improvement with combined physical and mental health treatment", admissionDate: "2023-07-03", roomNumber: "103" },
  { id: 4, registeredDate: "2023-08-11", name: "David Brown", age: 70, status: "Active", budget: "$2000-$2999", medicalConditions: ["Heart Disease"], ambulatory: "No", location: "321 Cedar Lane, San Francisco, CA 94132", gender: "Male", diagnosis: ["Coronary Artery Disease"], medications: ["Aspirin", "Statins"], careNeeds: ["Cardiac monitoring", "Assisted mobility"], notes: "Stable condition with medication management", admissionDate: "2023-08-11", roomNumber: "104" },
  { id: 5, registeredDate: "2023-09-19", name: "Eva Davis", age: 55, status: "Pending", budget: "$5000+", medicalConditions: ["Multiple Sclerosis"], ambulatory: "No", location: "654 Birch Road, San Francisco, CA 94121", gender: "Female", diagnosis: ["Multiple Sclerosis", "Chronic Fatigue"], medications: ["Copaxone", "Baclofen"], careNeeds: ["Physical therapy", "Daily living assistance"], notes: "Requires comprehensive support for daily activities", admissionDate: "2023-09-19", roomNumber: "105" },
  { id: 6, registeredDate: "2023-10-27", name: "Frank Miller", age: 68, status: "Active", budget: "$3000-$3999", medicalConditions: ["Parkinson's Disease", "Hypertension"], ambulatory: "Yes", location: "987 Elm Street, San Francisco, CA 94118", gender: "Male", diagnosis: ["Parkinson's Disease", "Hypertension"], medications: ["Levodopa", "Amlodipine"], careNeeds: ["Movement therapy", "Medication management"], notes: "Maintains good mobility with regular exercise program", admissionDate: "2023-10-27", roomNumber: "106" },
  { id: 7, registeredDate: "2023-11-05", name: "Grace Wilson", age: 82, status: "Inactive", budget: "$4000-$4999", medicalConditions: ["Alzheimer's", "Osteoporosis"], ambulatory: "No", location: "147 Willow Way, San Francisco, CA 94116", gender: "Female", diagnosis: ["Alzheimer's Disease", "Osteoporosis"], medications: ["Donepezil", "Calcium supplements"], careNeeds: ["Memory care", "Fall prevention"], notes: "Requires 24-hour supervision and memory care support", admissionDate: "2023-11-05", roomNumber: "107" },
  { id: 8, registeredDate: "2023-12-13", name: "Henry Taylor", age: 75, status: "Active", budget: "$2000-$2999", medicalConditions: ["Stroke Recovery"], ambulatory: "No", location: "258 Spruce Court, San Francisco, CA 94127", gender: "Male", diagnosis: ["Post-stroke Syndrome"], medications: ["Warfarin", "Aspirin"], careNeeds: ["Speech therapy", "Physical rehabilitation"], notes: "Making steady progress in post-stroke rehabilitation", admissionDate: "2023-12-13", roomNumber: "108" },
  { id: 9, registeredDate: "2024-01-21", name: "Ivy Anderson", age: 63, status: "Pending", budget: "$3000-$3999", medicalConditions: ["Diabetes", "Kidney Disease"], ambulatory: "Yes", location: "369 Redwood Place, San Francisco, CA 94131", gender: "Female", diagnosis: ["Type 2 Diabetes", "Chronic Kidney Disease"], medications: ["Insulin", "ACE inhibitors"], careNeeds: ["Diabetes management", "Renal diet"], notes: "Requires careful monitoring of blood sugar and kidney function", admissionDate: "2024-01-21", roomNumber: "109" },
  { id: 10, registeredDate: "2024-02-29", name: "Jack Thomas", age: 77, status: "Active", budget: "$5000+", medicalConditions: ["Congestive Heart Failure"], ambulatory: "No", location: "741 Aspen Circle, San Francisco, CA 94123", gender: "Male", diagnosis: ["Congestive Heart Failure"], medications: ["Furosemide", "Beta blockers"], careNeeds: ["Cardiac monitoring", "Fluid management"], notes: "Stable with current medication regimen and monitoring", admissionDate: "2024-02-29", roomNumber: "110" },
]
